# Generated by Django 4.0.1 on 2022-01-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbidding',
            name='is_bid',
            field=models.BooleanField(default=False),
        ),
    ]
