# Generated by Django 4.0.1 on 2022-01-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding_app', '0004_alter_vendorbidding_service_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceName',
            new_name='Service',
        ),
        migrations.RenameField(
            model_name='vendorbidding',
            old_name='service_name',
            new_name='service',
        ),
        migrations.AlterField(
            model_name='vendorbidding',
            name='value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
