# Generated by Django 4.0.1 on 2022-01-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding_app', '0006_alter_vendorbidding_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorbidding',
            name='is_bid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vendorbidding',
            name='value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
